package lattice

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

func GenerateEvaluator(ir SemanticIR, fixture Fixture, outDir string) (ArtifactBinding, error) {
	if ir.Schema != IRScheme { return ArtifactBinding{}, fmt.Errorf("unexpected semantic IR schema %q", ir.Schema) }
	if err := EnsureCallerOwnedOutput(outDir); err != nil { return ArtifactBinding{}, err }
	if err := ValidateFixture(fixture, ir); err != nil { return ArtifactBinding{}, err }
	var b strings.Builder
	b.WriteString("// Code generated by gooo-improvement-dominance-lattice; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	fmt.Fprintf(&b, "const Schema = %q\n", EvaluatorSchema)
	fmt.Fprintf(&b, "const CaseID = %q\n", fixture.CaseID)
	fmt.Fprintf(&b, "const SourceDigest = %q\n", ir.SourceDigest)
	fmt.Fprintf(&b, "const SemanticIRDigest = %q\n", DigestBytes(mustJSON(ir)))
	b.WriteString("\nvar IndicatorIDs = []string{\n")
	for _, indicator := range ir.Indicators { fmt.Fprintf(&b, "\t%q,\n", indicator.ID) }
	b.WriteString("}\n\n")
	b.WriteString("// EvaluateContract intentionally returns a vector contract, never a score.\n")
	b.WriteString("func EvaluateContract() string { return \"delta=after-before; per-indicator partial order\" }\n")
	path := filepath.Join(outDir, "evaluator.go")
	data := []byte(b.String())
	if err := WriteBytes(path, data); err != nil { return ArtifactBinding{}, err }
	if err := ValidateGeneratedGo(path); err != nil { return ArtifactBinding{}, err }
	digest, bytes, err := DigestFile(path)
	if err != nil { return ArtifactBinding{}, err }
	return ArtifactBinding{Stage: "GENERATED_GO_EVALUATOR", Path: path, Digest: digest, Bytes: len(bytes)}, nil
}

func mustJSON(value any) []byte {
	data, _ := json.Marshal(value)
	return data
}

func RenderDossierMarkdown(dossier Dossier) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Gooo Improvement Dominance Lattice Dossier")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "decision: `%s`\n", dossier.Decision)
	fmt.Fprintf(&b, "source_digest: `%s`\n", dossier.SourceDigest)
	fmt.Fprintf(&b, "contract_digest: `%s`\n", dossier.ContractDigest)
	fmt.Fprintln(&b, "decision_path: `delta=after-before -> per-indicator vector -> hard guardrails -> Pareto/partial-order state`")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Canonical cases")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| case | class | state | relation | action | candidate |")
	fmt.Fprintln(&b, "|---|---|---|---|---|---|")
	for _, receipt := range dossier.Receipts {
		c := receipt.Candidate
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n", receipt.CaseID, receipt.Class, c.State, c.Relation, c.Action, c.CandidateID)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Per-indicator observations")
	fmt.Fprintln(&b)
	for _, receipt := range dossier.Receipts {
		fmt.Fprintf(&b, "### %s\n\n", receipt.CaseID)
		fmt.Fprintln(&b, "| indicator | before | after | delta | direction | observation | role | proof | guardrail | budget |")
		fmt.Fprintln(&b, "|---|---:|---:|---:|---|---|---|---|---|---:|")
		for _, indicator := range receipt.Candidate.Indicators {
			budget := "none"; if indicator.Budget != nil { budget = strconv.Itoa(*indicator.Budget) }
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", indicator.IndicatorID, pointerString(indicator.Before), pointerString(indicator.After), pointerString(indicator.Delta), indicator.Direction, indicator.Observation, indicator.Role, indicator.ProofChoice, indicator.Guardrail, budget)
		}
		if len(receipt.Candidate.Unknown) > 0 { fmt.Fprintln(&b); fmt.Fprintln(&b, "unknown coordinates:"); for _, u := range receipt.Candidate.Unknown { fmt.Fprintf(&b, "- stage=`%s`, step=`%s`, reason=`%s`, unknown_class=`%s`, next_operation=`%s`, blocked_by=`%s`\n", u.Stage, u.Step, u.Reason, u.UnknownClass, u.NextOperation, strings.Join(u.BlockedBy, ",")) } }
		if len(receipt.Candidate.Violations) > 0 { fmt.Fprintln(&b); fmt.Fprintln(&b, "violations:"); for _, v := range receipt.Candidate.Violations { fmt.Fprintf(&b, "- %s: %s\n", v.Kind, v.Reason) } }
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "## Exact runtime observations")
	fmt.Fprintln(&b)
	r := dossier.Runtime
	fmt.Fprintln(&b, "| field | value |")
	fmt.Fprintln(&b, "|---|---:|")
	fmt.Fprintf(&b, "| compile wall_ms | %d |\n| compile peak_rss_kib | %d |\n| build wall_ms | %d |\n| build peak_rss_kib | %d |\n| test wall_ms | %d |\n| test peak_rss_kib | %d |\n| conformance wall_ms | %d |\n| conformance peak_rss_kib | %d |\n| integration wall_ms | %d |\n| integration peak_rss_kib | %d |\n", r.Compile.WallMs, r.Compile.PeakRSSKib, r.Build.WallMs, r.Build.PeakRSSKib, r.Test.WallMs, r.Test.PeakRSSKib, r.Conformance.WallMs, r.Conformance.PeakRSSKib, r.Integration.WallMs, r.Integration.PeakRSSKib)
	fmt.Fprintf(&b, "| tests_executed | %d |\n| tests_reused | %d |\n| tests_skipped | %d |\n| generated_artifact_files | %d |\n| generated_artifact_bytes | %d |\n| descendant_directories | %d |\n| regular_files_root_readme_excluded | %d |\n| go_files | %d |\n| go_physical_lines | %d |\n| gooo_files | %d |\n| gooo_physical_lines | %d |\n", r.TestsExecuted, r.TestsReused, r.TestsSkipped, r.GeneratedArtifacts, r.GeneratedBytes, r.Inventory.DescendantDirectories, r.Inventory.RegularFiles, r.Inventory.GoFiles, r.Inventory.GoPhysicalLines, r.Inventory.GoooFiles, r.Inventory.GoooPhysicalLines)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Authority boundary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "`%s`\n\n", r.OperationalRefuted)
	fmt.Fprintln(&b, "| authority | count |")
	fmt.Fprintln(&b, "|---|---:|")
	fmt.Fprintf(&b, "| runtime_input_reads | %d |\n| repository_writes | %d |\n| apply | %d |\n| commit | %d |\n| merge | %d |\n| tag | %d |\n| release | %d |\n| cross_project_required_gates | %d |\n", r.Authority.RuntimeInputReads, r.Authority.RepositoryWrites, r.Authority.Apply, r.Authority.Commit, r.Authority.Merge, r.Authority.Tag, r.Authority.Release, r.Authority.CrossProjectRequiredGates)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "local_validation_commands:")
	for _, command := range r.LocalValidationCommands { fmt.Fprintf(&b, "- `%s`\n", command) }
	return b.String()
}
